name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install backend dependencies
        working-directory: src/backend
        run: npm install

      - name: Start backend server
        working-directory: src/backend
        run: npm start

      - name: Install frontend dependencies
        working-directory: src/frontend
        run: npm install

      - name: Start frontend server
        working-directory: src/frontend
        run: npm run dev
