name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install src file dependencies
        working-directory: src
        run: npm install
        
      - name: Install frontend dependencies
        working-directory: src/frontend
        run: npm install
        
      - name: Install backend dependencies
        working-directory: src/backend
        run: npm install
        
      - name: Start backend and frontend server
        working-directory: src
        run: npm start
