name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install backend dependencies
        run: |
          cd src/backend
          npm install

      - name: Start backend server
        run: |
          cd src/backend
          npm start

      - name: Install frontend dependencies
        run: |
          cd src/frontend
          npm install

      - name: Start frontend server
        run: |
          cd src/frontend
          npm run dev
