name: CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install src file dependencies
        working-directory: src
        run: npm install
        
      - name: Install frontend dependencies
        working-directory: src/frontend
        run: npm install
        
      - name: Install backend dependencies
        working-directory: src/backend
        run: |
          npm install
          touch .env
          echo "MONGO_DB=${{ github.MONGO_DB }}" >> .env
          echo "PORT=${{ github.PORT }}" >> .env
          echo "JWT_SECRET=${{ github.JWT_SECRET }}" >> .env
          echo "SESSION_SECRET=${{ github.SESSION_SECRET }}" >> .env
          npm install
          npm run build --if-present
          npm run test --if-present
          
                  
      - name: Start backend and frontend server
        working-directory: src
        run: npm start
