name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
uses: actions/checkout@v4
uses: actions/setup-node@v2

      
run: |
        cd src/backend
        touch .env
        echo NODE_ENV=${{ vars.MONGO_DB}} >> .env
        echo NODE_ENV=${{ vars.PORT}} >> .env
         echo NODE_ENV=${{ vars.JWT_SECRET}} >> .env
        echo NODE_ENV=${{ vars.SESSION_SECRET}} >> .env
        npm install
        npm run build --if-present
        npm run test  --if-present